//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto25._10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public int RA { get; set; }
        public int Curso { get; set; }
        public string Nome { get; set; }
        public string CodigoTelefone { get; set; }
        public string Endereco { get; set; }
    
        public virtual Curso Curso1 { get; set; }
        public virtual Telefone Telefone { get; set; }
    }
}
