//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto25._10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matriculas_abertas
    {
        public int Id { get; set; }
        public int Curso { get; set; }
        public int Professor { get; set; }
        public System.TimeSpan Horario { get; set; }
    
        public virtual Curso Curso1 { get; set; }
        public virtual Professor Professor1 { get; set; }
    }
}
